spring:
    datasource:
      url: jdbc:postgresql://dpg-cjd1tb2nip6c73aaa13g-a.frankfurt-postgres.render.com/moviematch
      username: moviematch_user
      password: RgzcdbcH5w5ZKpiEjhWkLpCV4sak8SqL
    jpa:
      hibernate:
        ddl-auto: update

# Remove these debug properties in production!
debug: true
logging:
  level:
    org.springframework.security.web: DEBUG


movie-match:
  authorization:
    jwt:
      public-key: certificate/public.pem
      private-key: certificate/private.pem
  provider:
    the-movie-db:
      api-key: 0b5c632fd58d000a27736409177ef13a
      api-token: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwYjVjNjMyZmQ1OGQwMDBhMjc3MzY0MDkxNzdlZjEzYSIsInN1YiI6IjY0ZGE5YWZhZjQ5NWVlMDI4ZjY1OTA1NyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.v1Im4HTqaSm-mC4su1N3-08k7NO3sRoH74VJVTSjbPA